### ISSUE TITLE
启动报错 kc.sh相关

### ISSUE THREAD

**Issue by skret028** [ztelliot/keycloak-justauth#2]
用yanfeiwuji的启动命令，和简单的启动命令，都会报kc.sh相关的错，我看了下在dockerfile里
`RUN /opt/keycloak/bin/kc.sh build`
好像是没有错的，路径和命令都对，不知道错误原因是啥？

启动命令如下：
yanfeiwuji用mysql版本
`docker run -d \
--name=keycloak-justauth \
--net=dockernet \
--ip 172.18.0.25 \
-p 27080:8080 \
--restart=always \
-e KEYCLOAK_USER=admin \
-e KEYCLOAK_PASSWORD=admin \
-e DB_VENDOR=mysql \
-e DB_ADDR=172.18.0.3 \
-e DB_PORT=3306 \
-e DB_DATABASE=keycloak \
-e DB_USER=keycloak \
-e DB_PASSWORD=keycloak \
-e TZ=Asia/Shanghai \
ztelliot/keycloak-justauth:latest`

简易版本
`docker run -d \
--name=keycloak-justauth \
--net=dockernet \
--ip 172.18.0.25 \
-p 27080:8080 \
--restart=always \
-e TZ=Asia/Shanghai \
ztelliot/keycloak-justauth:latest`

错误内容如下：

> :
>   Start the server in development mode for local development or testing:
>       $ kc.sh start-dev
>   Building an optimized server runtime:
>       $ kc.sh build <OPTIONS>
>   Start the server in production mode:
>       $ kc.sh start <OPTIONS>
>   Enable auto-completion to bash/zsh:
>       $ source <(kc.sh tools completion)
>   Please, take a look at the documentation for more details before deploying in
> production.
> Use "kc.sh start --help" for the available options when starting the server.
> Use "kc.sh <command> --help" for more information about other commands.
> Keycloak - Open Source Identity and Access Management
> Find more information at: https://www.keycloak.org/docs/latest
> Usage:
> kc.sh [OPTIONS] [COMMAND]
> Use this command-line tool to manage your Keycloak cluster.
> Make sure the command is available on your "PATH" or prefix it with "./" (e.g.:
> "./kc.sh") to execute from the current folder.
> Options:
> -cf, --config-file <file>
>                      Set the path to a configuration file. By default, configuration properties are
>                        read from the "keycloak.conf" file in the "conf" directory.
> -h, --help           This help message.
> -v, --verbose        Print out error details when running this command.
> -V, --version        Show version information
> 
> :
>   build                   Creates a new and optimized server image.
>   start                   Start the server.
>   start-dev               Start the server in development mode.
>   export                  Export data from realms to a file or directory.
>   import                  Import data from a directory or a file.
>   show-config             Print out the current configuration.
>   tools                   Utilities for use and interaction with the server.
>     completion            Generate bash/zsh completion script for kc.sh.

**Comment by skret028** [comment]
再看了下rxrw和yfwj的dockerfile，里面没有
`RUN /opt/keycloak/bin/kc.sh build`
会是这句的问题么？

**Comment by ztelliot** [comment]
不好意思之前都没看到 issue，Quarkus 和 WildFly 部署差异较大，建议参考 [官方文档](https://www.keycloak.org/getting-started/getting-started-docker) 。
